### PR TITLE
Users and roles

### PR DESCRIPTION
**Pull request by Br3nda**
# What has changed and why?
closes https://github.com/ServiceInnovationLab/pancake-backend/issues/14
closes https://github.com/ServiceInnovationLab/pancake-frontend/issues/434

# How to test this change

- [x] has automated tests
- [ ] at least one a reviewer ran the code
- [ ] updated API docs

### CODE REVIEW

**Comment by Br3nda** [comment]
The User edit form needs the most work -- but generally, it's all there with User roles, Users belonging to councils, and User policies defining who can do what


image
image

image

**Comment by dlouise64** [comment]
@Br3nda I have created a council, role, and created a user via console. Thats working fine, but I'm unable to see a button in the admin to edit a the user, or to add a council

**Comment by Br3nda** [comment]
I've pair-ed with @dlouise64  to work out what's going on - she didn't have any existing users in the db so the migration didn't set any users as admin/DIA role.

**Comment by dlouise64** [comment]
@Br3nda Awesome

**Pull request merged**
